version: '2.0'
services:
  registry:
    image: registry:2
    environment:
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/fullchain.pem
      - REGISTRY_HTTP_TLS_KEY=/certs/privkey.pem
      - REGISTRY_HTTP_ADDR=0.0.0.0:443
    ports:
      - 5000:443
    volumes:
      - ./registry-data:/var/lib/registry
      - ./certs/fullchain.pem:/certs/fullchain.pem
      - ./certs/privkey.pem:/certs/privkey.pem
    networks:
      - registry-ui-net

  ui:
    image: joxit/docker-registry-ui:latest
    environment:
      - REGISTRY_TITLE=My Private Docker Registry
      - SINGLE_REGISTRY=true
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs/fullchain.pem:/etc/nginx/certs/fullchain.pem
      - ./certs/privkey.pem:/etc/nginx/certs/privkey.pem
    ports:
      - 443:443
    depends_on:
      - registry
    networks:
      - registry-ui-net

networks:
  registry-ui-net: